declare module 'bcrypt';
declare module '@fastify/cookie';
declare module 'fastify-formbody';
declare module 'fastify-nodemailer';
declare module 'fastify-sequelize';
declare module 'http-errors';
declare module 'lodash.get';
declare module 'nodemailer-mailgun-transport';
declare module 'pg';
