export interface Daily {
  checkTimeEt: string;
  commercialScore: number | null;
  dataQualityGrade: string;
  date: number | null;
  dateChecked: string;
  dateModified: string;
  death: number | null;
  deathConfirmed: number | null;
  deathIncrease: number | null;
  deathProbable: number | null;
  fips: string;
  grade: string;
  hash: string;
  hospitalized: number | null;
  hospitalizedCumulative: number | null;
  hospitalizedCurrently: number | null;
  hospitalizedIncrease: number | null;
  inIcuCumulative: number | null;
  inIcuCurrently: number | null;
  lastUpdateEt: string;
  negative: number | null;
  negativeIncrease: number | null;
  negativeRegularScore: number | null;
  negativeScore: number | null;
  negativeTestsAntibody: number | null;
  negativeTestsPeopleAntibody: number | null;
  negativeTestsViral: number | null;
  onVentilatorCumulative: number | null;
  onVentilatorCurrently: number | null;
  pending: number | null;
  positive: number | null;
  positiveCasesViral: number | null;
  positiveIncrease: number | null;
  positiveScore: number | null;
  positiveTestsAntibody: number | null;
  positiveTestsAntigen: number | null;
  positiveTestsPeopleAntibody: number | null;
  positiveTestsPeopleAntigen: number | null;
  positiveTestsViral: number | null;
  posNeg: number | null;
  recovered: number | null;
  score: number | null;
  state: string;
  total: number | null;
  totalTestEncountersViral: number | null;
  totalTestResults: number | null;
  totalTestResultsIncrease: number | null;
  totalTestResultsSource: string;
  totalTestsAntibody: number | null;
  totalTestsAntigen: number | null;
  totalTestsPeopleAntibody: number | null;
  totalTestsPeopleAntigen: number | null;
  totalTestsPeopleViral: number | null;
  totalTestsViral: number | null;
}
