/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Schema {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Schema`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  email: string;
  message: string;
  name: string;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Schema`'s JSON-Schema
 * via the `definition` "sms".
 */
export interface Sms {
  fromEmail: string;
  message: string;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Schema`'s JSON-Schema
 * via the `definition` "user".
 */
export interface User {
  email: string;
  id?: number;
  password?: string;
  [k: string]: unknown;
}
